# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: BUILD & TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dc: [ldc-latest, dmd-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run test-01
        run: dub run serverino:test-01

      - name: Run test-02
        run: dub run serverino:test-02

      - name: Build examples
        run: dub build --root=examples/01_hello_world/
              && dub build --root=examples/02_priority/
              && dub build --root=examples/03_form/
              && dub build --root=examples/04_html_dom/
              && dub build --root=examples/05_websocket_echo/
              && dub build --root=examples/06_websocket_noise_stream/
              && dub build --root=examples/07_websocket_callback/
